# DS4B 101-P: PYTHON FOR DATA SCIENCE AUTOMATION ----
# Environment Setup ----

# Conda Environment Setup Instructions ----
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
# 
#    conda env create -f 000_environment_setup/01_conda_environment.yml
#    conda env update --file 000_environment_setup/01_conda_environment.yml --prune
#    conda env export --name ds4b_101p > envname.yml
#    conda env remove --name ds4b_101p
#    conda env list
#    
#    pip freeze | grep -vE "^(pip|setuptools|wheel|pkg-resources)==.*$" > requirements.txt
#
# Alternative Using pip & virtual environments:
#  - Create empty virtual environment:
#      Mac: python3 -m venv ds4b_101_p
#      Windows: python -m venv ds4b_101_p
#  - Activate env:
#      source ds4b_101_p activate
#      (if this doesn't work, use Command Palette > Select Python Interpreter > ds4b_101_p)
#  - Install the requirements.txt
#      pip install -r 000_environment_setup/requirements.txt
#  - Adding packages from requirements.txt
#      Mac: where python
#      Windows: which python
#      path/to/python -m pip install
#  - Freezing dependencies
#      pip freeze > requirements.txt
#      Unix/Linux: pip freeze | grep -vE "^(pip|setuptools|wheel|pkg-resources)==.*$" > requirements.txt
#      Windows: pip freeze | Select-String -NotMatch "^(pip|setuptools|wheel|pkg-resources)==.*$" | Out-File -Encoding utf8 requirements.txt
# 
# To activate this environment, use
#
#     $ conda activate xxxl_mmix_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate
#
# Please update conda by running
#
#     $ conda update -n base -c defaults conda
#
# Or to minimize the number of packages updated during conda update use
#
#      conda install conda=25.3.1
# Update conda certificates
#
# conda install certifi
#
# setx SSL_CERT_FILE "%CONDA_PREFIX%\Library\ssl\cert.pem"
#

name: xxxl_mmix_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - pip
  - pip:
      # Core Data
      - scikit-misc==0.1.3
      - numpy==1.20.2
      - pandas==1.2.2

      # R Data
      - plydata==0.4.3
      # - siuba==0.0.24
      # - datatable

      # Visualization
      - matplotlib==3.3.4
      - plotly==4.14.3

      # EDA
      - pandas-profiling
      - ppscore==1.2.0
      - pyjanitor==0.20.14

      # Modeling & Machine Learning
      - statsmodels
      # - nltk==3.5
      # - h2o==3.32.0.3
      # - pycaret==2.3.0
      - scikit-learn==0.23.2
      # - xgboost==0.90
      # - lightgbm==3.1.1
      # - catboost==0.24.4
      # - sklearn-pandas==2.0.4

      # Database
      - sqlalchemy==1.4.7

      # Excel
      - xlsxwriter==1.3.7
      - openpyxl

